"""
Markdown 报告生成器
"""
from datetime import datetime
from pathlib import Path
from typing import Any, Dict

from ..models import ScanResult, Severity, Vulnerability


class MarkdownReporter:
    """
    Markdown 报告生成器

    生成格式化的 Markdown 报告，适合：
    - 粘贴到 GitHub Issues
    - 嵌入文档
    - 邮件发送
    """

    SEV_ORDER = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]

    def generate(self, result: ScanResult, output_path: Path):
        content = self._build_markdown(result)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content, encoding="utf-8")

    def _build_markdown(self, result: ScanResult) -> str:
        lines = [
            "# 🔍 WVS v19 扫描报告",
            "",
            f"**目标:** `{result.target.url}`  \n"
            f"**时间:** {result.scan_time.strftime('%Y-%m-%d %H:%M:%S') if result.scan_time else datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  \n"
            f"**耗时:** {result.duration:.1f}s  \n"
            f"**请求数:** {result.requests_made}",
            "",
        ]

        if not result.vulnerabilities:
            lines.extend([
                "## ✅ 结果",
                "",
                "**扫描完成，未发现漏洞。**",
                "",
            ])
        else:
            lines.extend([
                "## ⚠️ 漏洞统计",
                "",
                self._build_severity_table(result),
                "",
            ])

            lines.extend(["## 📋 漏洞详情", ""])

            for i, v in enumerate(result.vulnerabilities, 1):
                lines.extend(self._build_vuln_section(v, i))

        lines.extend([
            "---",
            f"*Generated by WVS v19.0.0 on {datetime.now().isoformat()}*",
        ])

        return "\n".join(lines)

    def _build_severity_table(self, result: ScanResult) -> str:
        lines = [
            "| 严重级别 | 数量 |",
            "|----------|------|",
        ]
        for sev in self.SEV_ORDER:
            count = result.severity_count.get(sev.lower(), 0)
            lines.append(f"| {sev} | {count} |")
        lines.append(f"| **TOTAL** | **{len(result.vulnerabilities)}** |")
        return "\n".join(lines)

    def _build_vuln_section(self, v: Vulnerability, i: int) -> list:
        badge_map = {
            "critical": "🔴 CRITICAL",
            "high": "🔴 HIGH",
            "medium": "🟡 MEDIUM",
            "low": "🔵 LOW",
            "info": "⚪ INFO",
        }
        badge = badge_map.get(v.severity.value, v.severity.value.upper())
        lines = [
            f"### {i}. {badge} — {v.title}",
            "",
            f"| 属性 | 值 |",
            f"|------|----|",
            f"| **类型** | `{v.type.value}` |",
            f"| **URL** | `{v.url}` |",
            f"| **参数** | `{v.parameter or '-'}` ({v.parameter_type or 'query'}) |",
            f"| **方法** | `{v.method or 'GET'}` |",
            f"| **置信度** | `{v.confidence.value}` |",
        ]
        if v.payload:
            escaped_payload = v.payload.replace("`", "\\`")
            lines.append(f"| **Payload** | `{escaped_payload[:100]}` |")
        if v.evidence:
            lines.append(f"| **证据** | {v.evidence[:200]} |")
        lines.append("")

        if v.description:
            lines.extend([f"**描述:** {v.description[:400]}", ""])
        if v.recommendation:
            lines.extend([f"**修复建议:** {v.recommendation[:400]}", ""])
        if v.references:
            lines.append("**参考链接:**")
            for ref in v.references[:5]:
                lines.append(f"- {ref}")
            lines.append("")

        return lines
