"""HTML 报告生成器"""
from typing import List
from pathlib import Path
from datetime import datetime

from ..vuln.base import Vulnerability, Severity


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>漏洞扫描报告 - {{ scan_id }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { 
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Microsoft YaHei', sans-serif;
            background: #f5f5f5; 
            color: #333;
            line-height: 1.6;
        }
        .container { max-width: 1200px; margin: 0 auto; padding: 20px; }
        .header { 
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white; 
            padding: 40px; 
            border-radius: 10px;
            margin-bottom: 30px;
        }
        .header h1 { font-size: 2.5em; margin-bottom: 10px; }
        .header p { opacity: 0.9; }
        .stats { 
            display: grid; 
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }
        .stat-card {
            background: white;
            padding: 25px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            text-align: center;
        }
        .stat-card .number {
            font-size: 3em;
            font-weight: bold;
            margin-bottom: 5px;
        }
        .stat-card.critical .number { color: #C0392B; }
        .stat-card.high .number { color: #E74C3C; }
        .stat-card.medium .number { color: #E67E22; }
        .stat-card.low .number { color: #27AE60; }
        .vuln-list { background: white; border-radius: 10px; padding: 30px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        .vuln-list h2 { margin-bottom: 20px; color: #333; }
        .vuln-item {
            border-left: 4px solid;
            padding: 20px;
            margin-bottom: 20px;
            background: #f9f9f9;
            border-radius: 0 8px 8px 0;
        }
        .vuln-item.critical { border-color: #C0392B; }
        .vuln-item.high { border-color: #E74C3C; }
        .vuln-item.medium { border-color: #E67E22; }
        .vuln-item.low { border-color: #27AE60; }
        .vuln-item h3 { margin-bottom: 10px; display: flex; align-items: center; gap: 10px; }
        .severity-badge {
            padding: 4px 12px;
            border-radius: 20px;
            font-size: 0.75em;
            font-weight: bold;
            color: white;
        }
        .severity-badge.CRITICAL { background: #C0392B; }
        .severity-badge.HIGH { background: #E74C3C; }
        .severity-badge.MEDIUM { background: #E67E22; }
        .severity-badge.LOW { background: #27AE60; }
        .vuln-meta { margin: 10px 0; }
        .vuln-meta code {
            background: #e8e8e8;
            padding: 2px 8px;
            border-radius: 4px;
            font-family: 'Consolas', monospace;
            word-break: break-all;
        }
        .vuln-section { margin-top: 15px; }
        .vuln-section h4 { color: #666; font-size: 0.9em; margin-bottom: 5px; }
        .remediation {
            background: #e8f4fd;
            padding: 15px;
            border-radius: 5px;
            border-left: 3px solid #3498db;
        }
        .footer {
            text-align: center;
            padding: 30px;
            color: #999;
            margin-top: 30px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🛡️ 漏洞扫描报告</h1>
            <p>扫描目标: <strong>{{ target }}</strong></p>
            <p>扫描时间: {{ scan_time }}</p>
            <p>报告ID: {{ scan_id }}</p>
        </div>
        
        <div class="stats">
            <div class="stat-card critical">
                <div class="number">{{ counts.CRITICAL }}</div>
                <div>严重漏洞</div>
            </div>
            <div class="stat-card high">
                <div class="number">{{ counts.HIGH }}</div>
                <div>高危漏洞</div>
            </div>
            <div class="stat-card medium">
                <div class="number">{{ counts.MEDIUM }}</div>
                <div>中危漏洞</div>
            </div>
            <div class="stat-card low">
                <div class="number">{{ counts.LOW }}</div>
                <div>低危漏洞</div>
            </div>
        </div>
        
        <div class="vuln-list">
            <h2>📋 漏洞详情 (共 {{ total }} 个)</h2>
            {{ vuln_items }}
        </div>
        
        <div class="footer">
            <p>Generated by WVS (Web Vulnerability Scanner)</p>
        </div>
    </div>
</body>
</html>
"""


class HTMLReportGenerator:
    """HTML 报告生成器"""
    
    def generate(self, scan_id: str, target: str, vulns: List[Vulnerability]) -> str:
        """生成 HTML 报告"""
        counts = self._count_by_severity(vulns)
        vuln_items_html = self._render_vuln_items(vulns)
        
        html = HTML_TEMPLATE.replace("{{ scan_id }}", scan_id)
        html = html.replace("{{ target }}", target)
        html = html.replace("{{ scan_time }}", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
        html = html.replace("{{ counts.CRITICAL }}", str(counts["CRITICAL"]))
        html = html.replace("{{ counts.HIGH }}", str(counts["HIGH"]))
        html = html.replace("{{ counts.MEDIUM }}", str(counts["MEDIUM"]))
        html = html.replace("{{ counts.LOW }}", str(counts["LOW"]))
        html = html.replace("{{ total }}", str(len(vulns)))
        html = html.replace("{{ vuln_items }}", vuln_items_html)
        
        return html
    
    def save(self, scan_id: str, target: str, vulns: List[Vulnerability], output_dir: Path) -> Path:
        """保存报告到文件"""
        html = self.generate(scan_id, target, vulns)
        output_path = output_dir / f"{scan_id}.html"
        output_path.write_text(html, encoding="utf-8")
        return output_path
    
    def _count_by_severity(self, vulns: List[Vulnerability]) -> dict:
        """按严重等级统计"""
        counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "INFO": 0}
        for v in vulns:
            counts[v.severity.name] = counts.get(v.severity.name, 0) + 1
        return counts
    
    def _render_vuln_items(self, vulns: List[Vulnerability]) -> str:
        """渲染漏洞列表"""
        if not vulns:
            return "<p style='text-align:center;color:#999;'>未发现漏洞</p>"
        
        items = []
        for v in vulns:
            item = f"""
            <div class="vuln-item {v.severity.name.lower()}">
                <h3>
                    <span class="severity-badge {v.severity.name}">{v.severity.label_cn}</span>
                    {v.name}
                </h3>
                <div class="vuln-meta">
                    <strong>URL:</strong> <code>{v.url}</code>
                </div>
                <div class="vuln-meta">
                    <strong>Payload:</strong> <code>{v.payload}</code>
                </div>
                <div class="vuln-section">
                    <h4>漏洞描述</h4>
                    <p>{v.description}</p>
                </div>
                <div class="vuln-section remediation">
                    <h4>修复建议</h4>
                    <p>{v.remediation}</p>
                </div>
                <div class="vuln-meta" style="margin-top:10px;color:#999;font-size:0.9em;">
                    置信度: {v.confidence * 100:.0f}% | CVE: {', '.join(v.cve_ids) if v.cve_ids else 'N/A'}
                </div>
            </div>
            """
            items.append(item)
        return "\n".join(items)
